/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrywatnaEnergiaDlaRezydencjiRouteImport } from './routes/prywatna-energia-dla-rezydencji'
import { Route as PrivateEnergySystemRouteImport } from './routes/private-energy-system'
import { Route as DziekujemyRouteImport } from './routes/dziekujemy'
import { Route as IndexRouteImport } from './routes/index'

const PrywatnaEnergiaDlaRezydencjiRoute =
  PrywatnaEnergiaDlaRezydencjiRouteImport.update({
    id: '/prywatna-energia-dla-rezydencji',
    path: '/prywatna-energia-dla-rezydencji',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivateEnergySystemRoute = PrivateEnergySystemRouteImport.update({
  id: '/private-energy-system',
  path: '/private-energy-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DziekujemyRoute = DziekujemyRouteImport.update({
  id: '/dziekujemy',
  path: '/dziekujemy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dziekujemy': typeof DziekujemyRoute
  '/private-energy-system': typeof PrivateEnergySystemRoute
  '/prywatna-energia-dla-rezydencji': typeof PrywatnaEnergiaDlaRezydencjiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dziekujemy': typeof DziekujemyRoute
  '/private-energy-system': typeof PrivateEnergySystemRoute
  '/prywatna-energia-dla-rezydencji': typeof PrywatnaEnergiaDlaRezydencjiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dziekujemy': typeof DziekujemyRoute
  '/private-energy-system': typeof PrivateEnergySystemRoute
  '/prywatna-energia-dla-rezydencji': typeof PrywatnaEnergiaDlaRezydencjiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dziekujemy'
    | '/private-energy-system'
    | '/prywatna-energia-dla-rezydencji'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dziekujemy'
    | '/private-energy-system'
    | '/prywatna-energia-dla-rezydencji'
  id:
    | '__root__'
    | '/'
    | '/dziekujemy'
    | '/private-energy-system'
    | '/prywatna-energia-dla-rezydencji'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DziekujemyRoute: typeof DziekujemyRoute
  PrivateEnergySystemRoute: typeof PrivateEnergySystemRoute
  PrywatnaEnergiaDlaRezydencjiRoute: typeof PrywatnaEnergiaDlaRezydencjiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prywatna-energia-dla-rezydencji': {
      id: '/prywatna-energia-dla-rezydencji'
      path: '/prywatna-energia-dla-rezydencji'
      fullPath: '/prywatna-energia-dla-rezydencji'
      preLoaderRoute: typeof PrywatnaEnergiaDlaRezydencjiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-energy-system': {
      id: '/private-energy-system'
      path: '/private-energy-system'
      fullPath: '/private-energy-system'
      preLoaderRoute: typeof PrivateEnergySystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dziekujemy': {
      id: '/dziekujemy'
      path: '/dziekujemy'
      fullPath: '/dziekujemy'
      preLoaderRoute: typeof DziekujemyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DziekujemyRoute: DziekujemyRoute,
  PrivateEnergySystemRoute: PrivateEnergySystemRoute,
  PrywatnaEnergiaDlaRezydencjiRoute: PrywatnaEnergiaDlaRezydencjiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
